namespace Nettention.Proud
{
	public enum ErrorType
	{
		Ok = 0,
		Unexpected = 1,
		AlreadyConnected = 2,
		TCPConnectFailure = 3,
		InvalidSessionKey = 4,
		EncryptFail = 5,
		DecryptFail = 6,
		ConnectServerTimeout = 7,
		ProtocolVersionMismatch = 8,
		NotifyServerDeniedConnection = 9,
		ConnectServerSuccessful = 10,
		DisconnectFromRemote = 11,
		DisconnectFromLocal = 12,
		DangerousArgumentWarning = 13,
		UnknownAddrPort = 14,
		ServerNotReady = 15,
		ServerPortListenFailure = 16,
		AlreadyExists = 17,
		PermissionDenied = 18,
		BadSessionGuid = 19,
		InvalidCredential = 20,
		InvalidHeroName = 21,
		LoadDataPreceded = 22,
		AdjustedGamerIDNotFilled = 23,
		NoHero = 24,
		UnitTestFailed = 25,
		P2PUdpFailed = 26,
		ReliableUdpFailed = 27,
		ServerUdpFailed = 28,
		NoP2PGroupRelation = 29,
		ExceptionFromUserFunction = 30,
		UserRequested = 31,
		InvalidPacketFormat = 32,
		TooLargeMessageDetected = 33,
		CannotEncryptUnreliableMessage = 34,
		ValueNotExist = 35,
		TcpCrisisDetected = 36,
		TimeOut = 37,
		LoadedDataNotFound = 38,
		SendQueueIsHeavy = 39,
		TooSlowHeartbeatWarning = 40,
		CompressFail = 41,
		LocalSocketCreationFailed = 42,
		NoneAvailableInPortPool = 43,
		InvalidPortPool = 44,
		InvalidHostID = 45,
		MessageOverload = 46,
		DatabaseAccessFailed = 47
	}
}
