namespace Nettention.Proud
{
	internal enum MessageType
	{
		None = 0,
		Rmi = 1,
		UserMessage = 2,
		Hla = 3,
		ConnectServerTimedout = 4,
		NotifyServerConnectionHint = 5,
		NotifyCSEncryptedSessionKey = 6,
		NotifyCSSessionKeySuccess = 7,
		NotifyServerConnectionRequestData = 8,
		NotifyProtocolVersionMismatch = 9,
		NotifyServerDeniedConnection = 10,
		NotifyServerConnectSuccess = 11,
		RequestStartServerHolepunch = 12,
		ServerHolepunch = 13,
		ServerHolepunchAck = 14,
		NotifyHolepunchSuccess = 15,
		NotifyClientServerUdpMatched = 16,
		PeerUdp_ServerHolepunch = 17,
		PeerUdp_ServerHolepunchAck = 18,
		PeerUdp_NotifyHolepunchSuccess = 19,
		ReliableUdp_Frame = 20,
		ReliableRelay1 = 21,
		UnreliableRelay1 = 22,
		UnreliableRelay1_RelayDestListCompressed = 23,
		LingerDataFrame1 = 24,
		ReliableRelay2 = 25,
		UnreliableRelay2 = 26,
		LingerDataFrame2 = 27,
		UnreliablePing = 28,
		SpeedHackDetectorPing = 29,
		UnreliablePong = 30,
		ArbitaryTouch = 31,
		PeerUdp_PeerHolepunch = 32,
		PeerUdp_PeerHolepunchAck = 33,
		P2PUnreliablePing = 34,
		P2PUnreliablePong = 35,
		S2CRoutedMulticast1 = 36,
		S2CRoutedMulticast2 = 37,
		Encrypted_Reliable = 38,
		Encrypted_UnReliable = 39,
		Compressed = 40,
		RequestReceiveSpeedAtReceiverSide_NoRelay = 41,
		ReplyReceiveSpeedAtReceiverSide_NoRelay = 42,
		NotifyConnectionPeerRequestData = 43,
		NotifyCSP2PDisconnected = 44,
		NotifyConnectPeerRequestDataSucess = 45,
		NotifyCSConnectionPeerSuccess = 46,
		Ignore = 47,
		RequestServerConnectionHint = 48,
		PolicyRequest = 49,
		P2PReliablePing = 50,
		P2PReliablePong = 51
	}
}
