public class AnimNameCfg
{
	public static string[] DauNoiLucList = new string[13]
	{
		"VC_DAU_NOI_LUC_KHOE_0", "VC_DAU_NOI_LUC_KHOE_1", "VC_DAU_NOI_LUC_KHOE_2", "VC_DAU_NOI_LUC_YEU_0", "VC_DAU_NOI_LUC_YEU_1", "VC_DAU_NOI_LUC_YEU_2", "VC_DAU_NOI_LUC_KHOE_0_TO_VC_DAU_NOI_LUC_KHOE_1", "VC_DAU_NOI_LUC_KHOE_1_TO_VC_DAU_NOI_LUC_KHOE_2", "VC_DAU_NOI_LUC_KHOE_2_TO_VC_DAU_NOI_LUC_KHOE_0", "VC_DAU_NOI_LUC_YEU_0_TO_VC_DAU_NOI_LUC_YEU_1",
		"VC_DAU_NOI_LUC_YEU_1_TO_VC_DAU_NOI_LUC_YEU_2", "VC_DAU_NOI_LUC_YEU_2_TO_VC_DAU_NOI_LUC_YEU_0", "VC_CHARGE"
	};
}
