public enum ERROR_CODE
{
	OK = 0,
	DISPLAY_MESSAGE = 1,
	ACCOUNT_DA_TON_TAI = 2,
	SAI_MAT_KHAU = 3,
	ACCOUNT_CHUA_TON_TAI = 4,
	MAT_DONG_BO = 5,
	DA_DANG_NHAP_TAI_KHOAN = 6,
	GAME_VERSION_KHONG_DU = 7,
	WAIT_FOR_ANOTHER_USER = 8,
	BANG_CHIEN_VAO_THANH_FAIL = 9
}
